#!/usr/bin/env python3
#
# In unit tests, calls to run 'kubectl' come here.
# A test case puts the Kubernetes responses it wants in a temporary folder, and we just print them.

import os
from pathlib import Path
import re
import sys

args = " ".join(sys.argv[1:])
if re.match("get pods (-n default|--all-namespaces) -o json", args):
    kind = "pods"
elif re.match("get pods (-n default|--all-namespaces)", args):
    kind = "pod_statuses"
elif re.match("get jobs (-n default|--all-namespaces) -o json", args):
    kind = "jobs"
elif re.match("get nodes -o json", args):
    kind = "nodes"
else:
    sys.exit(f"Unhandled command line: {args}")

mockdir = Path(os.environ["KUBEQL_MOCKDIR"])
content = mockdir.joinpath(kind).read_text()
print(content)